[build]

publish = "public/"
command = "hugo -d public"

[build.environment]
HUGO_VERSION = "0.64.1"

[[headers]]
	for = "/*"
	[headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = """
        geolocation none;
        midi none;
        notifications none;
        push none;
        sync-xhr none;
        microphone none;
        camera none;
        magnetometer none;
        gyroscope none;
        speaker self;
        vibrate none;
        fullscreen self;
    """

    # "style-src unsafe-inline:" Cf https://github.com/letsencrypt/website/issues/950
    # "connect-src https://d4twhgtvn0ff5.cloudfront.net/" for stats graphs
    # "img-src data: blob:" is for Plotly download feature

    Content-Security-Policy = """
    default-src
        'none';
    style-src
        'unsafe-inline'
        'self';
    script-src
        'self';
    img-src
        'self'
        data:
        blob:;
    frame-src
        https://www.youtube-nocookie.com;
    font-src
        'self';
    connect-src
        'self'
        https://d4twhgtvn0ff5.cloudfront.net/;
    form-action
        'none';
    """

[[headers]]
	for = "/repository"
	[headers.values]
    Referrer-Policy = "strict-origin"
[[headers]]
	for = "/:lang/repository"
	[headers.values]
    Referrer-Policy = "strict-origin"

[[headers]]
	for = "/donate"
	[headers.values]
    Content-Security-Policy = """
    default-src
        'none';
    style-src
        'unsafe-inline'
        'self';
    script-src
        'self'
        https://donorbox.org;
    img-src
        'self'
        https://www.paypalobjects.com;
    frame-src
        https://donorbox.org;
    font-src
        'self';
    """
    # "form-action" is NOT set, so it allows everything (it doesn't default to default-src). If restricted, It must allow at least www.paypal.com and it's redirects

[[redirects]]
from = "/jobs"
to = "https://www.abetterinternet.org/careers"
status = 302
force = false

[[redirects]]
from = "/certs"
to = "/certificates"
status = 302
force = false

[[redirects]]
from = "/howitworks"
to = "/getting-started"
status = 302
force = false

[[redirects]]
from = "/ct-logs"
to = "/docs/ct-logs"
status = 302
force = false

[[redirects]]
from = "/de/*"
to = "/de/404.html"
status = 404
force = false

[[redirects]]
from = "/es/*"
to = "/es/404.html"
status = 404
force = false

[[redirects]]
from = "/fr/*"
to = "/fr/404.html"
status = 404
force = false

[[redirects]]
from = "/id/*"
to = "/id/404.html"
status = 404
force = false

[[redirects]]
from = "/ja/*"
to = "/ja/404.html"
status = 404
force = false

[[redirects]]
from = "/ko/*"
to = "/ko/404.html"
status = 404
force = false

[[redirects]]
from = "/pt-br/*"
to = "/pt-br/404.html"
status = 404
force = false

[[redirects]]
from = "/ru/*"
to = "/ru/404.html"
status = 404
force = false

[[redirects]]
from = "/sr/*"
to = "/sr/404.html"
status = 404
force = false

[[redirects]]
from = "/sv/*"
to = "/sv/404.html"
status = 404
force = false

[[redirects]]
from = "/zh-cn/*"
to = "/zh-cn/404.html"
status = 404
force = false

[[redirects]]
from = "/zh-tw/*"
to = "/zh-tw/404.html"
status = 404
force = false

[[redirects]]
from = "/vi/*"
to = "/vi/404.html"
status = 404
force = false
